version: '3.8'
services:
  core-undangan:
    build: .
    container_name: core-undangan
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./src/data:/app/src/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge